# Generated by Django 5.2.8 on 2025-11-17 11:05

from django.db import migrations, models

import grandchallenge.components.models
import grandchallenge.core.storage
import grandchallenge.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0031_alter_workstation_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workstationimage",
            name="image",
            field=models.FileField(
                blank=True,
                help_text=".tar.gz archive of the container image produced from the command 'docker save IMAGE | gzip -c > IMAGE.tar.gz'. See https://docs.docker.com/engine/reference/commandline/save/",
                max_length=255,
                storage=grandchallenge.core.storage.PrivateS3Storage(),
                upload_to=grandchallenge.components.models.docker_image_path,
                validators=[
                    grandchallenge.core.validators.ExtensionValidator(
                        allowed_extensions=(".tar", ".tar.gz", ".tar.xz")
                    )
                ],
            ),
        ),
    ]
