# Generated by Django 5.2.8 on 2025-11-26 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0025_alter_imagefile_file"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="dicomimagesetupload",
            name="linked_object_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dicomimagesetupload_linked_object",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="dicomimagesetupload",
            name="linked_object_object_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="dicomimagesetupload",
            name="linked_socket_slug",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
