# Generated by Django 5.2.8 on 2025-11-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0025_alter_imagefile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="dicomimagesetupload",
            name="error_handling_data",
            field=models.JSONField(
                default=None,
                editable=False,
                help_text="Data about linked object and socket",
                null=True,
            ),
        ),
    ]
